package com.Twinhealth.pulseview

import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.sqrt

/**
 * POS (Plane Orthogonal to Skin) heart rate estimator.
 *
 * Faithful Kotlin port of `pos_hr_from_standardized_clip()` from
 * `pos_quality_gate.py` (Wang et al., 2017).
 *
 * Inputs are z-score-standardised crops in **DCHW** format — the same
 * format produced by [buildDchwChunks] from raw HWC crops.
 *
 * **Two roles in the pipeline:**
 *  1. Provide an independent HR estimate to guide [FftHrCalculator.computeHr]
 *     peak selection (peak-correction / harmonic-trap fix).
 *  2. Compute the divergence reliability gate: |efficientPhysHR - posHR| ≤ 10 BPM.
 *
 * ## Input format note
 *
 * POS expects raw (not diff-normalized) z-scored crops in DCHW order.
 * This is **different** from the diff-normalized NCHW chunks fed to the ONNX
 * model. The pipeline builds both from the same raw crops:
 *  - Raw HWC crops → z-score → DCHW chunks → [PosHrCalculator]
 *  - Raw HWC crops → diff-normalize → NCHW chunks → [OnnxInference]
 *
 * ## Butterworth filter
 *
 * The 4th-order Butterworth bandpass (0.75–2.5 Hz) IIR coefficients are
 * pre-computed from `scipy.signal.butter(4, [low/nyq, high/nyq], btype='bandpass')`
 * and hardcoded for fs=20 Hz and fs=30 Hz. For intermediate FPS values the
 * nearest set is used. `filtfilt` is implemented as two passes of a Direct-Form II
 * transposed (DF2T) filter — forward then backward — matching `scipy.signal.filtfilt`.
 */
object PosHrCalculator {

    // ── Butterworth IIR Coefficients ─────────────────────────────────────────
    // Generated by: scipy.signal.butter(4, [low/nyq, high/nyq], btype='bandpass')
    // where low=0.75 Hz, high=2.5 Hz. Length-9 arrays (4th-order bandpass = 8th-order IIR).

    /** Numerator (b) and denominator (a) for fs=20 Hz, 4th-order Butterworth [0.75, 2.5] Hz. */
    private val B_FS20 = doubleArrayOf(
        0.0030512214778501703, 0.0, -0.012204885911400681, 0.0, 0.01830732886710102,
        0.0, -0.012204885911400681, 0.0, 0.0030512214778501703
    )
    private val A_FS20 = doubleArrayOf(
        1.0, -5.957020417998657, 16.018902686389982, -25.412989414099787,
        26.024438771239982, -17.617416290365366, 7.700095151782779,
        -1.9880231035200770, 0.23260156647563962
    )

    /** Numerator (b) and denominator (a) for fs=30 Hz, 4th-order Butterworth [0.75, 2.5] Hz. */
    private val B_FS30 = doubleArrayOf(
        0.0007286360246298222, 0.0, -0.002914544098519289, 0.0, 0.004371816147778934,
        0.0, -0.002914544098519289, 0.0, 0.0007286360246298222
    )
    private val A_FS30 = doubleArrayOf(
        1.0, -6.753727352093504, 20.230617323116730, -35.111103512867025,
        38.620582455963934, -27.572407776455865, 12.478500528451416,
        -3.2737502144001183, 0.3813173074676029
    )

    // ── Steady-State Initial Conditions (zi) for filtfilt ─────────────────────
    // Generated by: scipy.signal.lfilter_zi(b, a)
    
    private val ZI_FS20 = doubleArrayOf(
        -0.003051221477863906, -0.003051221477882083, 0.009153664433398568,
        0.009153664433747632, -0.009153664433710846, -0.009153664433468862,
        0.003051221477826058, 0.0030512214778533647
    )
    private val ZI_FS30 = doubleArrayOf(
        -0.0007286360247305525, -0.000728636024050247, 0.002185908072431207,
        0.0021859080759679544, -0.002185908075701239, -0.002185908072923861,
        0.0007286360243384669, 0.0007286360246682325
    )

    // ─────────────────────────────────────────────────────────────────────────
    // Public API
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Compute POS HR from a single z-score-standardized clip.
     *
     * Matches the Python `pos_hr_from_standardized_clip(clip, fs)` signature and behavior.
     *
     * @param clip Array of frames (D), where each frame is a flat `FloatArray` of size `3 * H * W`
     *             containing the RGB channels in CHW layout (channel-first: R channels, then G, then B).
     * @param fs   Sampling frequency in Hz.
     * @return     POS HR in BPM, or null on failure.
     */
    fun posHrFromStandardizedClip(clip: Array<FloatArray>, fs: Double): Double? {
        if (clip.isEmpty()) return null
        val depth = clip.size
        if (depth < 2) return null
        val numElements = clip[0].size
        if (numElements % 3 != 0) return null
        val spatialSize = numElements / 3
        val height = sqrt(spatialSize.toDouble()).toInt()
        if (height * height != spatialSize) return null

        try {
            val rgbMean = computeSpatialMeans(clip)
            val hAcc = posProjection(rgbMean, fs)
            if (hAcc.all { it == 0.0 }) return null

            val (b, a) = selectCoefficients(fs)
            val zi = selectZi(fs)
            val filtered = filtfilt(b, a, hAcc, zi)

            val nfft = FftHrCalculator.nextPowerOf2(maxOf(filtered.size, 64))
            val (freqs, psd) = FftHrCalculator.computePeriodogram(filtered, fs, nfft)

            var bestIdx = -1
            var bestPower = -1.0
            for (k in freqs.indices) {
                if (freqs[k] >= 0.75 && freqs[k] <= 2.5) {
                    if (psd[k] > bestPower) {
                        bestPower = psd[k]
                        bestIdx = k
                    }
                }
            }
            if (bestIdx < 0) return null

            return freqs[bestIdx] * 60.0
        } catch (e: Exception) {
            return null
        }
    }

    /**
     * Compute spatial RGB means per frame from a DCHW input array.
     *
     * Shifts the clip to a strictly positive range by subtracting the global minimum,
     * adds 1e-6 to avoid zero-mean channels, and averages each channel over the H and W dims.
     *
     * Matches Step 1 and Step 2 of `pos_hr_from_standardized_clip`.
     */
    fun computeSpatialMeans(clip: Array<FloatArray>): Array<DoubleArray> {
        val depth = clip.size
        if (depth == 0) return emptyArray()
        val numElements = clip[0].size
        val spatialSize = numElements / 3

        // Find the global minimum across the entire clip
        var minVal = Double.MAX_VALUE
        for (frame in clip) {
            for (v in frame) {
                if (v < minVal) {
                    minVal = v.toDouble()
                }
            }
        }

        return Array(depth) { d ->
            val frame = clip[d]
            DoubleArray(3) { c ->
                var sum = 0.0
                val offset = c * spatialSize
                for (hw in 0 until spatialSize) {
                    val v = frame[offset + hw].toDouble() - minVal + 1e-6
                    sum += v
                }
                sum / spatialSize
            }
        }
    }

    /**
     * Apply sliding-window POS projection and overlap accumulation.
     *
     * Matches Step 3 of `pos_hr_from_standardized_clip`.
     */
    fun posProjection(rgbMean: Array<DoubleArray>, fs: Double): DoubleArray {
        val depth = rgbMean.size
        val l = ceil(1.6 * fs).toInt()
        val hAcc = DoubleArray(depth)

        for (n in 0 until depth) {
            val m = n - l
            if (m < 0) continue

            // window = rgbMean[m:n] -> shape (l, 3)
            val chMean = DoubleArray(3) { c ->
                var s = 0.0
                for (i in m until n) s += rgbMean[i][c]
                s / l
            }
            if (chMean[0] == 0.0 || chMean[1] == 0.0 || chMean[2] == 0.0) continue

            // Cn = window / chMean
            // S = P @ Cn.T -> shape (2, l)
            // where P = [[0, 1, -1], [-2, 1, 1]]
            val S0 = DoubleArray(l)
            val S1 = DoubleArray(l)
            for (j in 0 until l) {
                val frameIdx = m + j
                val cn0 = rgbMean[frameIdx][0] / chMean[0]
                val cn1 = rgbMean[frameIdx][1] / chMean[1]
                val cn2 = rgbMean[frameIdx][2] / chMean[2]

                S0[j] = cn1 - cn2
                S1[j] = -2.0 * cn0 + cn1 + cn2
            }

            val std0 = stdDev(S0)
            val std1 = stdDev(S1)
            if (std1 == 0.0) continue

            // h = S[0] + (std0/std1) * S[1]
            val ratio = std0 / std1
            var hMean = 0.0
            val h = DoubleArray(l) { j ->
                val v = S0[j] + ratio * S1[j]
                hMean += v
                v
            }
            hMean /= l
            for (j in 0 until l) {
                h[j] -= hMean
            }

            // Overlap accumulation
            for (j in 0 until l) {
                hAcc[m + j] += h[j]
            }
        }
        return hAcc
    }

    /**
     * Compute POS HR from a single flat DCHW clip of z-score-standardized crops.
     *
     * Delegates to [posHrFromStandardizedClip].
     */
    fun posHrFromDchw(
        clip: FloatArray,
        depth: Int,
        height: Int,
        width: Int,
        fs: Double = 30.0
    ): Double? {
        if (depth < 2 || height <= 0 || width <= 0) return null
        val spatialSize = height * width
        val frameSize = 3 * spatialSize
        if (clip.size != depth * frameSize) return null

        val clipArray = Array(depth) { d ->
            FloatArray(frameSize) { i ->
                clip[d * frameSize + i]
            }
        }
        return posHrFromStandardizedClip(clipArray, fs)
    }

    /**
     * Build z-score-normalized DCHW chunks from raw HWC crops.
     */
    fun buildDchwChunks(
        hwcFrames: List<FloatArray>,
        imgSize: Int = Preprocessor.IMG_SIZE,
        chunkDepth: Int = 160,
        stride: Int = 30
    ): List<Triple<FloatArray, Int, Int>> {
        val n = hwcFrames.size
        if (n == 0) return emptyList()

        val pixelsPerFrame = imgSize * imgSize * 3

        // ── Global z-score across all frames ────────────────────────────────────
        var sum = 0.0
        var sumSq = 0.0
        val total = n.toLong() * pixelsPerFrame
        for (frame in hwcFrames) {
            for (v in frame) {
                sum += v
                sumSq += v.toDouble() * v
            }
        }
        val mean = sum / total
        val variance = sumSq / total - mean * mean
        val std = sqrt(variance)
        val safeDivisor = if (std < 1e-10) 1e-10 else std

        // z-score every frame in-place (returns copy)
        val zFrames = hwcFrames.map { hwc ->
            FloatArray(pixelsPerFrame) { i -> ((hwc[i] - mean) / safeDivisor).toFloat() }
        }

        // ── Determine chunk windows ──────────────────────────────────────────────
        val effectiveDepth: Int
        val starts: List<Int>

        if (n < chunkDepth) {
            effectiveDepth = n
            starts = listOf(0)
        } else {
            effectiveDepth = chunkDepth
            starts = (0..(n - chunkDepth) step stride).toList()
        }

        val result = mutableListOf<Triple<FloatArray, Int, Int>>()
        val spatialSize = imgSize * imgSize

        for (start in starts) {
            val depth = minOf(effectiveDepth, n - start)
            if (depth < 2) break

            // Convert HWC frames to DCHW flat array:
            //   flatDCHW[d * 3 * S*S + c * S*S + p] = hwc[p * 3 + c]
            val flat = FloatArray(depth * 3 * spatialSize)
            for (d in 0 until depth) {
                val hwc = zFrames[start + d]
                val frameOffset = d * 3 * spatialSize
                for (p in 0 until spatialSize) {
                    val hwcBase = p * 3
                    for (c in 0 until 3) {
                        flat[frameOffset + c * spatialSize + p] = hwc[hwcBase + c]
                    }
                }
            }
            result.add(Triple(flat, depth, imgSize))
        }

        return result
    }

    /**
     * Compute the mean POS HR estimate across multiple DCHW chunks.
     */
    fun computePosHrFromChunks(
        dchwChunks: List<Triple<FloatArray, Int, Int>>,
        fs: Double = 30.0
    ): Double? {
        val validHrs = mutableListOf<Double>()
        for ((flat, depth, imgSize) in dchwChunks) {
            val hr = posHrFromDchw(flat, depth, imgSize, imgSize, fs)
            if (hr != null && hr >= 40.0 && hr <= 180.0) {
                validHrs.add(hr)
            }
        }
        return if (validHrs.isEmpty()) null else validHrs.average()
    }

    /**
     * Data class holding POS heart rate calculation results.
     */
    data class PosResult(
        val posHr: Double?,
        val totalChunks: Int,
        val validChunks: Int,
        val firstChunkDepth: Int
    )

    /**
     * Compute POS HR by downsampling frames and processing sliding windows sequentially.
     *
     * Saves memory by:
     * 1. Downsampling raw crops from [srcSize] to [dstSize] (e.g. 72 to 36) in HWC.
     * 2. Materializing only a single flat DCHW chunk at any one time, allowing the GC
     *    to reclaim flat array memory between sliding window evaluations.
     */
    fun computePosHr(
        rawCrops: List<FloatArray>,
        srcSize: Int = Preprocessor.IMG_SIZE,
        dstSize: Int = 36,
        chunkDepth: Int = 160,
        stride: Int = 30,
        fs: Double = 30.0
    ): PosResult {
        val n = rawCrops.size
        if (n == 0) return PosResult(null, 0, 0, 0)

        // 1. Downsample raw crops from srcSize to dstSize in HWC
        val downsampledCrops = if (srcSize == dstSize) {
            rawCrops
        } else {
            val factor = srcSize / dstSize
            rawCrops.map { hwc ->
                val dst = FloatArray(dstSize * dstSize * 3)
                for (y in 0 until dstSize) {
                    val srcY = y * factor
                    for (x in 0 until dstSize) {
                        val srcX = x * factor
                        val srcIdx = (srcY * srcSize + srcX) * 3
                        val dstIdx = (y * dstSize + x) * 3
                        dst[dstIdx] = hwc[srcIdx]
                        dst[dstIdx + 1] = hwc[srcIdx + 1]
                        dst[dstIdx + 2] = hwc[srcIdx + 2]
                    }
                }
                dst
            }
        }

        val pixelsPerFrame = dstSize * dstSize * 3

        // 2. Global z-score across all frames
        var sum = 0.0
        var sumSq = 0.0
        val total = n.toLong() * pixelsPerFrame
        for (frame in downsampledCrops) {
            for (v in frame) {
                sum += v
                sumSq += v.toDouble() * v
            }
        }
        val mean = sum / total
        val variance = sumSq / total - mean * mean
        val std = sqrt(variance)
        val safeDivisor = if (std < 1e-10) 1e-10 else std

        val zFrames = downsampledCrops.map { hwc ->
            FloatArray(pixelsPerFrame) { i -> ((hwc[i] - mean) / safeDivisor).toFloat() }
        }

        // 3. Sliding-window chunk bounds
        val effectiveDepth = if (n < chunkDepth) n else chunkDepth
        val starts = if (n < chunkDepth) listOf(0) else (0..(n - chunkDepth) step stride).toList()

        val validHrs = mutableListOf<Double>()
        val spatialSize = dstSize * dstSize
        val firstDepth = if (starts.isNotEmpty()) minOf(effectiveDepth, n - starts[0]) else 0

        for (start in starts) {
            val depth = minOf(effectiveDepth, n - start)
            if (depth < 2) break

            // Materialize a SINGLE flat chunk of size depth * 3 * spatialSize
            val flat = FloatArray(depth * 3 * spatialSize)
            for (d in 0 until depth) {
                val hwc = zFrames[start + d]
                val frameOffset = d * 3 * spatialSize
                for (p in 0 until spatialSize) {
                    val hwcBase = p * 3
                    for (c in 0 until 3) {
                        flat[frameOffset + c * spatialSize + p] = hwc[hwcBase + c]
                    }
                }
            }

            // Compute HR for this single chunk immediately and discard it
            val hr = posHrFromDchw(flat, depth, dstSize, dstSize, fs)
            if (hr != null && hr >= 40.0 && hr <= 180.0) {
                validHrs.add(hr)
            }
        }

        val posHr = if (validHrs.isEmpty()) null else validHrs.average()
        return PosResult(posHr, starts.size, validHrs.size, firstDepth)
    }


    // ─────────────────────────────────────────────────────────────────────────
    // Internal DSP helpers
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Select Butterworth IIR coefficient pair (b, a) closest to [fs].
     */
    internal fun selectCoefficients(fs: Double): Pair<DoubleArray, DoubleArray> {
        return if (abs(fs - 20.0) <= abs(fs - 30.0)) {
            Pair(B_FS20, A_FS20)
        } else {
            Pair(B_FS30, A_FS30)
        }
    }

    /**
     * Select Butterworth initial state coefficients (zi) closest to [fs].
     */
    internal fun selectZi(fs: Double): DoubleArray {
        return if (abs(fs - 20.0) <= abs(fs - 30.0)) {
            ZI_FS20
        } else {
            ZI_FS30
        }
    }

    /**
     * Zero-phase forward+backward IIR filter, matching `scipy.signal.filtfilt(b, a, x)`.
     */
    internal fun filtfilt(
        b: DoubleArray,
        a: DoubleArray,
        x: DoubleArray,
        zi: DoubleArray
    ): DoubleArray {
        val n = x.size
        if (n < 2) return x.copyOf()

        val ntaps = maxOf(b.size, a.size)
        val padLen = ntaps * 3

        if (n <= padLen) {
            val fwd = iirFilter(b, a, x)
            val rev = iirFilter(b, a, fwd.reversedArray())
            return rev.reversedArray()
        }

        // Build odd-reflection padded signal
        val padded = DoubleArray(n + 2 * padLen)
        // Left pad: 2*x[0] - x[padLen downTo 1]
        for (i in 0 until padLen) {
            padded[i] = 2.0 * x[0] - x[padLen - i]
        }
        // Copy original
        for (i in 0 until n) padded[padLen + i] = x[i]
        // Right pad: 2*x[n-1] - x[n-2 downTo n-1-padLen]
        for (i in 0 until padLen) {
            padded[padLen + n + i] = 2.0 * x[n - 1] - x[n - 2 - i]
        }

        // Forward filter with scaled zi
        val ziFwd = DoubleArray(zi.size) { zi[it] * padded[0] }
        val fwdPadded = iirFilter(b, a, padded, ziFwd)

        // Backward filter (reverse, filter with scaled zi, reverse)
        val revPadded = fwdPadded.reversedArray()
        val ziBwd = DoubleArray(zi.size) { zi[it] * revPadded[0] }
        val bwdPadded = iirFilter(b, a, revPadded, ziBwd).reversedArray()

        // Trim padding
        return DoubleArray(n) { bwdPadded[padLen + it] }
    }

    /**
     * Single-pass causal IIR filter using Direct-Form II Transposed (DF2T).
     */
    internal fun iirFilter(
        b: DoubleArray,
        a: DoubleArray,
        x: DoubleArray,
        zi: DoubleArray? = null
    ): DoubleArray {
        val nb = b.size
        val na = a.size
        val order = maxOf(nb, na) - 1
        val y = DoubleArray(x.size)
        val z = DoubleArray(order)  // delay line (state)

        if (zi != null) {
            System.arraycopy(zi, 0, z, 0, minOf(zi.size, order))
        }

        for (n in x.indices) {
            val xn = x[n]
            y[n] = b[0] * xn + z[0]
            for (i in 0 until order - 1) {
                val bCoeff = if (i + 1 < nb) b[i + 1] else 0.0
                val aCoeff = if (i + 1 < na) a[i + 1] else 0.0
                z[i] = bCoeff * xn - aCoeff * y[n] + z[i + 1]
            }
            val lastB = if (order < nb) b[order] else 0.0
            val lastA = if (order < na) a[order] else 0.0
            z[order - 1] = lastB * xn - lastA * y[n]
        }
        return y
    }

    /** Population standard deviation of a DoubleArray. */
    internal fun stdDev(arr: DoubleArray): Double {
        if (arr.isEmpty()) return 0.0
        var sum = 0.0
        var sumSq = 0.0
        for (v in arr) { sum += v; sumSq += v * v }
        val mean = sum / arr.size
        val variance = sumSq / arr.size - mean * mean
        return sqrt(maxOf(0.0, variance))
    }
}
